//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaticosWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ViaticosEntities3 : DbContext
    {
        public ViaticosEntities3()
            : base("name=ViaticosEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VehAutWeb> VehAutWeb { get; set; }
        public virtual DbSet<VehCab> VehCab { get; set; }
        public virtual DbSet<VehCabAnt> VehCabAnt { get; set; }
        public virtual DbSet<VehDet> VehDet { get; set; }
        public virtual DbSet<VehDetant> VehDetant { get; set; }
        public virtual DbSet<VehDetNew> VehDetNew { get; set; }
        public virtual DbSet<VehFacturacion> VehFacturacion { get; set; }
        public virtual DbSet<VehMae> VehMae { get; set; }
    }
}
