//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaticosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehCab
    {
        public int solcod { get; set; }
        public string tipo { get; set; }
        public Nullable<int> codveh { get; set; }
        public Nullable<decimal> kmant { get; set; }
        public Nullable<decimal> kmact { get; set; }
        public Nullable<decimal> km { get; set; }
        public Nullable<int> tipman { get; set; }
        public string observaciones { get; set; }
        public Nullable<int> codgrifo { get; set; }
        public Nullable<int> usureg { get; set; }
        public Nullable<System.DateTime> fegreg { get; set; }
        public string estado { get; set; }
        public string anno { get; set; }
        public string gercod { get; set; }
        public string arecod { get; set; }
        public Nullable<System.DateTime> fecaut { get; set; }
        public Nullable<int> usuaut { get; set; }
        public Nullable<System.DateTime> fecimp { get; set; }
        public Nullable<int> usuimp { get; set; }
        public Nullable<int> tipcom { get; set; }
        public Nullable<System.DateTime> fecrev { get; set; }
        public Nullable<int> usurev { get; set; }
        public Nullable<int> usuanu { get; set; }
        public Nullable<System.DateTime> fecanu { get; set; }
        public Nullable<int> codgrupo { get; set; }
    }
}
