//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaticosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehDet
    {
        public int item { get; set; }
        public Nullable<int> solcod { get; set; }
        public Nullable<int> codmot { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<System.DateTime> fecreg { get; set; }
        public string anno { get; set; }
        public string TipMed { get; set; }
        public Nullable<decimal> pu { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> cantidadmod { get; set; }
    }
}
