//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaticosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehFacturacion
    {
        public int Item { get; set; }
        public Nullable<int> IDGrupo { get; set; }
        public Nullable<System.DateTime> FecReg { get; set; }
        public Nullable<int> UsuCrea { get; set; }
        public Nullable<int> codgrifo { get; set; }
        public Nullable<System.DateTime> FecFac { get; set; }
        public string NroDoc { get; set; }
        public Nullable<int> NroSol { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Observaciones { get; set; }
        public string Estado { get; set; }
        public string RUC { get; set; }
        public string Periodo { get; set; }
    }
}
