//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViaticosWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehMae
    {
        public int Item { get; set; }
        public string Codact { get; set; }
        public string VehPla { get; set; }
        public Nullable<int> AreCod { get; set; }
        public Nullable<int> MarCod { get; set; }
        public Nullable<int> TipCod { get; set; }
        public Nullable<int> Vo2Cod { get; set; }
        public Nullable<decimal> VehKm { get; set; }
        public string VehEst { get; set; }
        public Nullable<decimal> VehAno { get; set; }
        public string Asignado { get; set; }
        public Nullable<System.DateTime> FecReg { get; set; }
        public string estado { get; set; }
        public Nullable<int> codemp { get; set; }
        public string celular { get; set; }
        public string fecini { get; set; }
        public string fecfin { get; set; }
        public string fecbaj { get; set; }
        public Nullable<int> VehUnid { get; set; }
    }
}
